# -*- coding: utf-8 -*-
"""CoffeeShop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iOzmV4K6D9rPBYIFihpcjM7EwAgkeRNv
"""

#Made by Solomon on 20/09/22
cost = 0
while(True):
  size=input("Do you want a small, medium or large cup of coffee? ")
  if(size=="small" or size=="Small"):
    cost+=2
    break
  elif(size=="medium" or size=="Medium"):
    cost+=3
    break
  elif(size=="large" or size=="Large"):
    cost+=4
    break
  else:
    print("You have chosen an option that does not exist")     
while(True):
  typec=input("What flavour do you want? Brewed, Espresso or Cold Brew? ")
  if(typec=="brewed" or typec=="Brewed"):
     break
  elif(typec=="espresso" or typec=="Espresso"): 
    cost+=-0.5
    break
  elif(typec=="cold brew" or typec=="Cold Brew" or typec=="Cold brew"):
    cost+=1
    break            
  else:
    print("You have chosen an option that does not exist")  
flavour=input("Do you want flavoured syrup? Yes or No? ")
if(flavour=="Yes" or flavour=="yes"):
  while(True):
    flavourt=input("Do you want hazelnut, vanilla or caramel? ")
    if(flavourt=="hazelnut" or flavourt=="Hazelnut" or flavourt=="vanilla" or flavourt=="Vanilla" or flavourt=="Caramel" or flavourt=="caramel"):
      cost+=0.5
      print("You have chosen a {} cup of {} with {} syrup".format(size, typec, flavourt))
      print("The cost is "+str(cost))
      cost+=cost*0.15
      print("The price with tip is "+str(cost))  
      break      
    else:
      print("You have chosen an option that does not exist") 
elif(flavour=="No"  or flavour=="no"): 
 print("You have chosen a {} cup of {} with no syrup".format(size, typec))
 print("The cost is "+str(cost))
 cost+=cost*0.15
 print("The price with tip is "+str(cost)) 
else:
  print("You have chosen an invalid option")